name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release 2>&1 | tee build/build.log

    - name: Check for warnings
      run: |
        # Fail if any compiler warnings are found in the build log
        if grep -i "warning:" build/build.log; then
          echo "Build contains warnings!"
          exit 1
        fi

    - name: Run iteration
      run: |
        ./build/iteration --graph-type undirected --edge-type unweighted --scale 8 --degree 8 --gen-type erdos_renyi
        ./build/iteration --graph-type directed --edge-type unweighted --scale 8 --degree 8 --gen-type erdos_renyi
        ./build/iteration --graph-type undirected --edge-type weighted --scale 8 --degree 8 --gen-type erdos_renyi
        ./build/iteration --graph-type directed --edge-type weighted --scale 8 --degree 8 --gen-type erdos_renyi

    - name: Run verify_undirected
      run: |
        ./build/verify_undirected --edge-type unweighted --scale 8 --degree 8 --gen-type erdos_renyi
        ./build/verify_undirected --edge-type weighted --scale 8 --degree 8 --gen-type erdos_renyi

    - name: Run dense packing check
      run: |
        ./build/packing

    - name: Run triangle counting tests
      run: |
        ./build/triangle_counting_test

    - name: Run breadth-first search tests
      run: |
        ./build/breadth_first_search_test

    - name: Test individual algorithm executables
      run: |
        # Test CPU algorithms
        ./build/tc --scale 6 --degree 3 --gen-type erdos_renyi
        ./build/bfs --scale 6 --degree 3 --gen-type erdos_renyi
        
        # Test threaded algorithms
        ./build/tc_threaded --scale 6 --degree 3 --gen-type erdos_renyi
        ./build/bfs_threaded --scale 6 --degree 3 --gen-type erdos_renyi